// This file contains little functions that is needed in various places. Instead of creating separate files, I have stored all of them in one place and exported from here

import getDb from "@/database/mongodb";

// Returns current semester using the current month value
export function getCurrentSemester():
  | "1st Semester"
  | "2nd Semester"
  | "3rd Semester"
  | "4th Semester" {
  const currentMonth = new Date().getMonth();

  return (
    (currentMonth >= 0 && currentMonth < 3 && "1st Semester") ||
    (currentMonth >= 3 && currentMonth < 6 && "2nd Semester") ||
    (currentMonth >= 6 && currentMonth < 9 && "3rd Semester") ||
    "4th Semester"
  );
}

// Returns newly generated roll and registration number
export async function getRollAndRegistrationNumber(
  department: "Computer Science" | "Mathematics" | "Physics" | "Chemistry"
) {
  const { students } = await getDb();
  // Roll number is generated by getting total count of active students from students collection
  const roll = (
    (await students.countDocuments({
      status: "Active",
      department: department,
    })) + 1
  )
    .toString()
    .padStart(4, "0"); // Return something like this 0001 if the student is first in the department
  const rollNum = department.slice(0, 3).toUpperCase() + roll; // something like PHY0001

  // Registration number is generated by adding the full year value before the registration number
  const registrationNumber = new Date().getFullYear().toString() + roll; // Returns 20260001
  return { rollNum, registrationNumber };
}

// Returns user's status
export async function getUserStatus({ email }: { email: string }) {
  const { users } = await getDb();
  const result = await users.findOne({ email }, { projection: { status: 1 } });

  return result?.status;
}

// Returns user's role
export async function getUserRole({ email }: { email: string }) {
  const { users } = await getDb();
  const result = await users.findOne({ email }, { projection: { role: 1 } });

  return result?.status;
}
